title: jao Minecraft Server Developer Documentation
description: jao Minecraft Server 開発者向けドキュメント
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: jao Minecraft Server
repo_url: 'https://github.com/jaoafa/developer-docs'
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
